### PR TITLE
[FEATURE] File glob matching for "excludeFiles" with proper caching

### PR DESCRIPTION
**Pull request by alexdiliberto**
This PR does the following:

- Implements glob matching for "excludeFiles" using [minimatch](https://github.com/isaacs/minimatch)
- Implements proper caching to ensure minimatch is only run once for each given relative path
- Tests the feature

Thanks to @rwjblue for all his help with this PR :+1:

### CODE REVIEW

**Comment by rwjblue** [comment]
LGTM!

**Comment by kellyselden** [comment]
Thanks for the PR!

**Comment by kellyselden** [comment]
version updated to 0.0.15 and published.

**Comment by rwjblue** [comment]
Awesome, thanks @kellyselden for the quick turn-around.

**Comment by rwjblue** [comment]
@teddyzenney - This should satisfy your PR from earlier also.

**Comment by teddyzeenny** [comment]
:+1: thanks everyone!

**Pull request merged**
